server:
  port: 18080
spring:
  application:
    name: dahua-test-graph
  ai:
    openai:
      base-url: http://localhost:11434
      api-key: ollama
      chat:
        options:
          model: qwen3:8b
          internal-tool-execution-enabled: true
      embedding:
        options:
          model: bge-large:335m
logging:
  level:
    root: debug