server:
  port: 18080
spring:
  application:
    name: dahua-test-graph
  datasource:
    url: jdbc:postgresql://20.12.0.38:5432/prptdb
    username: schedulerdb
    #    password: cG9zdGdyZXN0ZXN0Cg==
    #   password: ENC(uVHRDvJL/EBn+YXdnDKaNETgT5sKrU4F)
    password: LC@tyzy2025!
    driver-class-name: org.postgresql.Driver

  ai:
    openai:
      base-url: http://20.200.25.216:8080
      api-key: b8d5ca9f6f344058ba9d8cad089ac53d97a7a3e6021242638069e67bb6b09881
      chat:
        options:
          model: Qwen25-32B-1-test
          internal-tool-execution-enabled: false
          headers:
            Authorization: "Bearer b8d5ca9f6f344058ba9d8cad089ac53d97a7a3e6021242638069e67bb6b09881"
        completionsPath: /v1/chat/completion

milvus:
  host: 20.198.118.210 # Milvus 服务地址（默认本地）
  port: 19530 # Milvus gRPC 端口（默认19530）
  collectionName: docs06 # 向量集合名称（不存在时会自动创建）
  embeddingDimension: 1024  # 向量维度（必须与模型输出一致）

rerank:
  base-url: http://20.200.25.216:8080
  api-key: b8d5ca9f6f344058ba9d8cad089ac53d97a7a3e6021242638069e67bb6b09881
  rerankPath: "/rerank"
  model: Bge-rerank-v2-m3-test

jasypt:
  encryptor:
    password: Yld@123

logging:
  level:
    root: info


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.dahuaboke.mpda.tools.product.entity