jasypt:
  encryptor:
    password: Yld@123
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  application:
    name: ifund-bot
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.dahuaboke.mpda.bot.tools.entity,com.dahuaboke.mpda.bot.monitor.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


