server:
  port: 18080
spring:
  application:
    name: ai-code

  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-86e29d1b831d4959ae0a7a2ab0645d5b
      chat:
        options:
          model: qwen-plus
          internal-tool-execution-enabled: false

    mcp:
      client:
        enabled: true
        sse:
          connections:
            playwright:
              url: http://localhost:8931
              sse-endpoint: /sse

logging:
  level:
    root: info