server:
  port: 18080
spring:
  application:
    name: ai-code

  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: 
      chat:
        options:
          model: qwen-plus
          internal-tool-execution-enabled: false

logging:
  level:
    root: info
